[workspace]

[package]
name = "menu"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "menu"
test = false
bench = false

[features]
default = ["g_audio", "g_disp", "g_keys", "g_ani"]
g_radio = []
g_audio = []
g_disp = []
g_keys = []
g_ani = []
g_system = []

[dependencies]
bf5rh-abi = { path = "../../../abi" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
debug = true
panic = "abort"
