#![doc = "Peripheral access API for AT32F421XX_V2 microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 4;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn WWDT();
    fn PVM();
    fn ERTC();
    fn FLASH();
    fn CRM();
    fn EXTINT1_0();
    fn EXTINT3_2();
    fn EXTINT15_4();
    fn DMA1_Channel1();
    fn DMA1_Channel3_2();
    fn DMA1_Channel5_4();
    fn ADC_CMP();
    fn TMR1_BRK_OVF_TRG_HALL();
    fn TMR1_CH();
    fn TMR3();
    fn TMR6();
    fn ADC1_2();
    fn TMR14();
    fn TMR15();
    fn TMR16();
    fn TMR17();
    fn USART1();
    fn USART2();
    fn I2C1_EVT();
    fn I2C1_ERR();
    fn I2C2_EVT();
    fn I2C2_ERR();
    fn SPI1();
    fn SPI2();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 37] = [
    Vector { _handler: WWDT },
    Vector { _handler: PVM },
    Vector { _handler: ERTC },
    Vector { _handler: FLASH },
    Vector { _handler: CRM },
    Vector {
        _handler: EXTINT1_0,
    },
    Vector {
        _handler: EXTINT3_2,
    },
    Vector {
        _handler: EXTINT15_4,
    },
    Vector { _reserved: 0 },
    Vector {
        _handler: DMA1_Channel1,
    },
    Vector {
        _handler: DMA1_Channel3_2,
    },
    Vector {
        _handler: DMA1_Channel5_4,
    },
    Vector { _handler: ADC_CMP },
    Vector {
        _handler: TMR1_BRK_OVF_TRG_HALL,
    },
    Vector { _handler: TMR1_CH },
    Vector { _reserved: 0 },
    Vector { _handler: TMR3 },
    Vector { _handler: TMR6 },
    Vector { _handler: ADC1_2 },
    Vector { _handler: TMR14 },
    Vector { _handler: TMR15 },
    Vector { _handler: TMR16 },
    Vector { _handler: TMR17 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: USART1 },
    Vector { _handler: USART2 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: I2C1_EVT },
    Vector { _handler: I2C1_ERR },
    Vector { _handler: I2C2_EVT },
    Vector { _handler: I2C2_ERR },
    Vector { _handler: SPI1 },
    Vector { _handler: SPI2 },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - Window Watchdog interrupt"]
    WWDT = 0,
    #[doc = "1 - PVM interrupt connect to EXTI line16"]
    PVM = 1,
    #[doc = "2 - ERTC interrupt connect to EXTI line17_19"]
    ERTC = 2,
    #[doc = "3 - Flash global interrupt"]
    FLASH = 3,
    #[doc = "4 - CRM global interrupt"]
    CRM = 4,
    #[doc = "5 - EXINT Line1_0 interrupt"]
    EXTINT1_0 = 5,
    #[doc = "6 - EXINT Line3_2 interrupt"]
    EXTINT3_2 = 6,
    #[doc = "7 - EXINT Line15_4 interrupt"]
    EXTINT15_4 = 7,
    #[doc = "9 - DMA1 Channel1 global interrupt"]
    DMA1_Channel1 = 9,
    #[doc = "10 - DMA1 Channel2 global interrupt"]
    DMA1_Channel3_2 = 10,
    #[doc = "11 - DMA1 Channel3 global interrupt"]
    DMA1_Channel5_4 = 11,
    #[doc = "12 - ADC and CMP interrupt"]
    ADC_CMP = 12,
    #[doc = "13 - TMR1 overflow brake trigger hall interrupt"]
    TMR1_BRK_OVF_TRG_HALL = 13,
    #[doc = "14 - TMR1 channel interrupt"]
    TMR1_CH = 14,
    #[doc = "16 - TMR3 global interrupt"]
    TMR3 = 16,
    #[doc = "17 - TMR6 global interrupt"]
    TMR6 = 17,
    #[doc = "18 - ADC1 and ADC2 global interrupt"]
    ADC1_2 = 18,
    #[doc = "19 - TMR14 global interrupt"]
    TMR14 = 19,
    #[doc = "20 - TMR15 global interrupt"]
    TMR15 = 20,
    #[doc = "21 - TMR16 global interrupt"]
    TMR16 = 21,
    #[doc = "22 - TMR17 global interrupt"]
    TMR17 = 22,
    #[doc = "27 - USART1 global interrupt"]
    USART1 = 27,
    #[doc = "28 - USART2 global interrupt"]
    USART2 = 28,
    #[doc = "31 - I2C1 event interrupt"]
    I2C1_EVT = 31,
    #[doc = "32 - I2C1 error interrupt"]
    I2C1_ERR = 32,
    #[doc = "33 - I2C2 event interrupt"]
    I2C2_EVT = 33,
    #[doc = "34 - I2C2 error interrupt"]
    I2C2_ERR = 34,
    #[doc = "35 - SPI1 global interrupt"]
    SPI1 = 35,
    #[doc = "36 - SPI2 global interrupt"]
    SPI2 = 36,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "Power control"]
pub type Pwc = crate::Periph<pwc::RegisterBlock, 0x4000_7000>;
impl core::fmt::Debug for Pwc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwc").finish()
    }
}
#[doc = "Power control"]
pub mod pwc;
#[doc = "Clock and reset management"]
pub type Crm = crate::Periph<crm::RegisterBlock, 0x4002_1000>;
impl core::fmt::Debug for Crm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crm").finish()
    }
}
#[doc = "Clock and reset management"]
pub mod crm;
#[doc = "General purpose I/Os"]
pub type Gpioa = crate::Periph<gpioa::RegisterBlock, 0x4800_0000>;
impl core::fmt::Debug for Gpioa {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpioa").finish()
    }
}
#[doc = "General purpose I/Os"]
pub mod gpioa;
#[doc = "General purpose I/Os"]
pub type Gpiob = crate::Periph<gpioa::RegisterBlock, 0x4800_0400>;
impl core::fmt::Debug for Gpiob {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiob").finish()
    }
}
#[doc = "General purpose I/Os"]
pub use self::gpioa as gpiob;
#[doc = "General purpose I/Os"]
pub type Gpioc = crate::Periph<gpioa::RegisterBlock, 0x4800_0800>;
impl core::fmt::Debug for Gpioc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpioc").finish()
    }
}
#[doc = "General purpose I/Os"]
pub use self::gpioa as gpioc;
#[doc = "General purpose I/Os"]
pub type Gpiof = crate::Periph<gpioa::RegisterBlock, 0x4800_1400>;
impl core::fmt::Debug for Gpiof {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiof").finish()
    }
}
#[doc = "General purpose I/Os"]
pub use self::gpioa as gpiof;
#[doc = "EXINT"]
pub type Exint = crate::Periph<exint::RegisterBlock, 0x4001_0400>;
impl core::fmt::Debug for Exint {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Exint").finish()
    }
}
#[doc = "EXINT"]
pub mod exint;
#[doc = "DMA controller"]
pub type Dma1 = crate::Periph<dma1::RegisterBlock, 0x4002_0000>;
impl core::fmt::Debug for Dma1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dma1").finish()
    }
}
#[doc = "DMA controller"]
pub mod dma1;
#[doc = "Real-time clock"]
pub type Ertc = crate::Periph<ertc::RegisterBlock, 0x4000_2800>;
impl core::fmt::Debug for Ertc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ertc").finish()
    }
}
#[doc = "Real-time clock"]
pub mod ertc;
#[doc = "Watchdog"]
pub type Wdt = crate::Periph<wdt::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for Wdt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wdt").finish()
    }
}
#[doc = "Watchdog"]
pub mod wdt;
#[doc = "Window watchdog"]
pub type Wwdt = crate::Periph<wwdt::RegisterBlock, 0x4000_2c00>;
impl core::fmt::Debug for Wwdt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wwdt").finish()
    }
}
#[doc = "Window watchdog"]
pub mod wwdt;
#[doc = "Advanced timer"]
pub type Tmr1 = crate::Periph<tmr1::RegisterBlock, 0x4001_2c00>;
impl core::fmt::Debug for Tmr1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr1").finish()
    }
}
#[doc = "Advanced timer"]
pub mod tmr1;
#[doc = "General purpose timer"]
pub type Tmr3 = crate::Periph<tmr3::RegisterBlock, 0x4000_0400>;
impl core::fmt::Debug for Tmr3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr3").finish()
    }
}
#[doc = "General purpose timer"]
pub mod tmr3;
#[doc = "General purpose timer"]
pub type Tmr14 = crate::Periph<tmr14::RegisterBlock, 0x4000_2000>;
impl core::fmt::Debug for Tmr14 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr14").finish()
    }
}
#[doc = "General purpose timer"]
pub mod tmr14;
#[doc = "Advanced timer"]
pub type Tmr15 = crate::Periph<tmr15::RegisterBlock, 0x4001_4000>;
impl core::fmt::Debug for Tmr15 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr15").finish()
    }
}
#[doc = "Advanced timer"]
pub mod tmr15;
#[doc = "General purpose timer"]
pub type Tmr16 = crate::Periph<tmr16::RegisterBlock, 0x4001_4400>;
impl core::fmt::Debug for Tmr16 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr16").finish()
    }
}
#[doc = "General purpose timer"]
pub mod tmr16;
#[doc = "General purpose timer"]
pub type Tmr17 = crate::Periph<tmr16::RegisterBlock, 0x4001_4800>;
impl core::fmt::Debug for Tmr17 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr17").finish()
    }
}
#[doc = "General purpose timer"]
pub use self::tmr16 as tmr17;
#[doc = "Basic timer"]
pub type Tmr6 = crate::Periph<tmr6::RegisterBlock, 0x4000_1000>;
impl core::fmt::Debug for Tmr6 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr6").finish()
    }
}
#[doc = "Basic timer"]
pub mod tmr6;
#[doc = "Inter integrated circuit"]
pub type I2c1 = crate::Periph<i2c1::RegisterBlock, 0x4000_5400>;
impl core::fmt::Debug for I2c1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c1").finish()
    }
}
#[doc = "Inter integrated circuit"]
pub mod i2c1;
#[doc = "Inter integrated circuit"]
pub type I2c2 = crate::Periph<i2c1::RegisterBlock, 0x4000_5800>;
impl core::fmt::Debug for I2c2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c2").finish()
    }
}
#[doc = "Inter integrated circuit"]
pub use self::i2c1 as i2c2;
#[doc = "Serial peripheral interface"]
pub type Spi1 = crate::Periph<spi1::RegisterBlock, 0x4001_3000>;
impl core::fmt::Debug for Spi1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi1").finish()
    }
}
#[doc = "Serial peripheral interface"]
pub mod spi1;
#[doc = "Serial peripheral interface"]
pub type Spi2 = crate::Periph<spi1::RegisterBlock, 0x4000_3800>;
impl core::fmt::Debug for Spi2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi2").finish()
    }
}
#[doc = "Serial peripheral interface"]
pub use self::spi1 as spi2;
#[doc = "Universal synchronous asynchronous receiver transmitter"]
pub type Usart1 = crate::Periph<usart1::RegisterBlock, 0x4001_3800>;
impl core::fmt::Debug for Usart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart1").finish()
    }
}
#[doc = "Universal synchronous asynchronous receiver transmitter"]
pub mod usart1;
#[doc = "Universal synchronous asynchronous receiver transmitter"]
pub type Usart2 = crate::Periph<usart1::RegisterBlock, 0x4000_4400>;
impl core::fmt::Debug for Usart2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart2").finish()
    }
}
#[doc = "Universal synchronous asynchronous receiver transmitter"]
pub use self::usart1 as usart2;
#[doc = "Analog to digital converter"]
pub type Adc = crate::Periph<adc::RegisterBlock, 0x4001_2400>;
impl core::fmt::Debug for Adc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc").finish()
    }
}
#[doc = "Analog to digital converter"]
pub mod adc;
#[doc = "Comparator"]
pub type Cmp = crate::Periph<cmp::RegisterBlock, 0x4001_001c>;
impl core::fmt::Debug for Cmp {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cmp").finish()
    }
}
#[doc = "Comparator"]
pub mod cmp;
#[doc = "Debug support"]
pub type Debug = crate::Periph<debug::RegisterBlock, 0xe004_2000>;
impl core::fmt::Debug for Debug {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Debug").finish()
    }
}
#[doc = "Debug support"]
pub mod debug;
#[doc = "CRC calculation unit"]
pub type Crc = crate::Periph<crc::RegisterBlock, 0x4002_3000>;
impl core::fmt::Debug for Crc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crc").finish()
    }
}
#[doc = "CRC calculation unit"]
pub mod crc;
#[doc = "Flash memory controler"]
pub type Flash = crate::Periph<flash::RegisterBlock, 0x4002_2000>;
impl core::fmt::Debug for Flash {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Flash").finish()
    }
}
#[doc = "Flash memory controler"]
pub mod flash;
#[doc = "System configuration controller"]
pub type Scfg = crate::Periph<scfg::RegisterBlock, 0x4001_0000>;
impl core::fmt::Debug for Scfg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Scfg").finish()
    }
}
#[doc = "System configuration controller"]
pub mod scfg;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "PWC"]
    pub pwc: Pwc,
    #[doc = "CRM"]
    pub crm: Crm,
    #[doc = "GPIOA"]
    pub gpioa: Gpioa,
    #[doc = "GPIOB"]
    pub gpiob: Gpiob,
    #[doc = "GPIOC"]
    pub gpioc: Gpioc,
    #[doc = "GPIOF"]
    pub gpiof: Gpiof,
    #[doc = "EXINT"]
    pub exint: Exint,
    #[doc = "DMA1"]
    pub dma1: Dma1,
    #[doc = "ERTC"]
    pub ertc: Ertc,
    #[doc = "WDT"]
    pub wdt: Wdt,
    #[doc = "WWDT"]
    pub wwdt: Wwdt,
    #[doc = "TMR1"]
    pub tmr1: Tmr1,
    #[doc = "TMR3"]
    pub tmr3: Tmr3,
    #[doc = "TMR14"]
    pub tmr14: Tmr14,
    #[doc = "TMR15"]
    pub tmr15: Tmr15,
    #[doc = "TMR16"]
    pub tmr16: Tmr16,
    #[doc = "TMR17"]
    pub tmr17: Tmr17,
    #[doc = "TMR6"]
    pub tmr6: Tmr6,
    #[doc = "I2C1"]
    pub i2c1: I2c1,
    #[doc = "I2C2"]
    pub i2c2: I2c2,
    #[doc = "SPI1"]
    pub spi1: Spi1,
    #[doc = "SPI2"]
    pub spi2: Spi2,
    #[doc = "USART1"]
    pub usart1: Usart1,
    #[doc = "USART2"]
    pub usart2: Usart2,
    #[doc = "ADC"]
    pub adc: Adc,
    #[doc = "CMP"]
    pub cmp: Cmp,
    #[doc = "DEBUG"]
    pub debug: Debug,
    #[doc = "CRC"]
    pub crc: Crc,
    #[doc = "FLASH"]
    pub flash: Flash,
    #[doc = "SCFG"]
    pub scfg: Scfg,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            pwc: Pwc::steal(),
            crm: Crm::steal(),
            gpioa: Gpioa::steal(),
            gpiob: Gpiob::steal(),
            gpioc: Gpioc::steal(),
            gpiof: Gpiof::steal(),
            exint: Exint::steal(),
            dma1: Dma1::steal(),
            ertc: Ertc::steal(),
            wdt: Wdt::steal(),
            wwdt: Wwdt::steal(),
            tmr1: Tmr1::steal(),
            tmr3: Tmr3::steal(),
            tmr14: Tmr14::steal(),
            tmr15: Tmr15::steal(),
            tmr16: Tmr16::steal(),
            tmr17: Tmr17::steal(),
            tmr6: Tmr6::steal(),
            i2c1: I2c1::steal(),
            i2c2: I2c2::steal(),
            spi1: Spi1::steal(),
            spi2: Spi2::steal(),
            usart1: Usart1::steal(),
            usart2: Usart2::steal(),
            adc: Adc::steal(),
            cmp: Cmp::steal(),
            debug: Debug::steal(),
            crc: Crc::steal(),
            flash: Flash::steal(),
            scfg: Scfg::steal(),
        }
    }
}
